# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

before_install:
- brew update
- gem install xcpretty
- brew outdated carthage || brew upgrade carthage

script:
- carthage bootstrap
- xcodebuild | xcpretty
- xcodebuild -scheme Triassic-macOS -target Triassic-macOS -configuration release | xcpretty
- xcodebuild test -scheme Triassic-macOS | xcpretty
- pod lib lint
# - swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)
