# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

before_install:
- brew update
- brew outdated xctool || brew upgrade xctool
- brew install carthage

script:
- carthage bootstrap --platform Mac
- xcodebuild
- xcodebuild -scheme Triassic-macOS -target Triassic-macOS -configuration release

after_success:
  - bash <(curl -s https://codecov.io/bash)
